USE db_escola_T

--LISTAR OS 3 PRIMEIROS ALUNOS
SELECT TOP 3 matricula FROM tb_aluno

--LISTA AS MATRICULAS DOS ALUNOS EM ORDEN CRESCENTE
SELECT TOP 1 matricula 
FROM tb_aluno
ORDER BY nome DESC;


--LISTA OS ID's DOS 3 PRIMEIROS ALUNOS QUE FORAM RECEM CADASTRADOS 
SELECT nome, cpf 
FROM tb_aluno
WHERE nome = 'Hugo';

--LISTA O NOME DA ESCOLA TORLONI
SELECT nome
FROM tb_escola
WHERE nome = 'Torloni';

--MOSTRE AS TURMA QUE TEM O NOME SEDUC 
SELECT nome_turma
FROM tb_turma
WHERE nome_turma = 'Seduc';

--EXIBA SOMETE OS 2 ALUNOS EM ORDEM DO MAIS RECENTE PARA O MENOS RECENTE
SELECT TOP 2 *
FROM tb_aluno
ORDER BY id DESC;

--MOSTRE QUANTOS ALUNOS EXISTE NA BASE 
SELECT COUNT (matricula) AS qtd_alunos FROM tb_aluno;

--MOSTRE OS ALUNOS MAIS NOVOS
SELECT MAX(data_nasc) AS idade_mais_nova FROM tb_aluno;

--MOSTRE OS ALUNOS MAIS VELHOS 
SELECT MIN(data_nasc) AS idade_mais_velha FROM tb_aluno;

--EXIBA A IDADE MAIS VELHA E A IDADE MAIS NOVA EM UMA UNICA CONSULTA 
SELECT MIN(data_nasc) AS idade_mais_velha, MAX(data_nasc) AS idade_mais_nova FROM tb_aluno;

--SELECIONAMOS O PRIMEIRO REGISTRO DA TEBELA 
SELECT TOP 1 nome, data_nasc 
FROM tb_aluno
--ORDENAMOS ELA POR DATA DE NASCIMENTO PARA QUE A IDADE MAIS VELHA SEJA A PRIMEIRA A APARECER
ORDER BY data_nasc;  

--MEDIA ARITMÉDICA DE NOTA QUE VALE NAS PROVAS
SELECT AVG(nota) AS media_nota FROM tb_prova;

--EXIBA A SOMA DOS ID's DE TURMA
SELECT SUM(id) FROM tb_aluno;

SELECT * FROM tb_aluno;

--MOSTRA OS NOMES DO ALUNOS MAIS NOVOS
SELECT MAX(data_nasc) AS idade_mais_novo, nome
FROM tb_aluno
GROUP BY nome
ORDER BY idade_mais_novo DESC;

--EXIBIR QUANTAS TURMAS TEM NO PERIODO DA TARDE
SELECT COUNT(periodo)
FROM tb_turma
WHERE periodo = 'Tarde';